version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=stoik
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
  api:
    container_name: slugifyer
    image: slugifyer:latest
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - './config.yaml:/config.yaml'
volumes:
  db:
    driver: local